import { StyleSheet } from "react-native-unistyles";

export const styles = StyleSheet.create((theme, rt) => {
  const isDark = rt.themeName === "dark";

  return {
    container: {
      flex: 1,
    },
    scrollView: {
      flex: 1,
    },
    contentContainer: {
      flex: 1,
      padding: theme.spacing.lg,
      paddingTop: theme.spacing.custom(20),
      paddingBottom: theme.spacing.custom(90),
    },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: theme.spacing["2xl"],
    },
    backButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.surface.glass,
    },
    headerSpacer: {
      width: 40,
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: "600",
      letterSpacing: 0.5,
      color: theme.text.primary,
    },
    iconContainer: {
      alignItems: "center",
      marginBottom: theme.spacing.xl,
    },
    successIcon: {
      width: 100,
      height: 100,
      borderRadius: 50,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: theme.accent.green,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.3,
      shadowRadius: 16,
      elevation: 10,
    },
    title: {
      fontSize: 32,
      fontWeight: "800",
      textAlign: "center",
      marginBottom: theme.spacing.custom(12),
      letterSpacing: -1,
      color: theme.text.primary,
    },
    subtitle: {
      fontSize: 16,
      textAlign: "center",
      marginBottom: theme.spacing["3xl"],
      lineHeight: 24,
      opacity: 0.8,
      color: theme.text.secondary,
    },
    passcodeSection: {
      marginBottom: theme.spacing.xl,
    },
    passcodeCard: {
      borderRadius: 32,
      borderWidth: 1,
      padding: theme.spacing.xl,
      alignItems: "center",
      overflow: "hidden",
      position: "relative",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.2,
      shadowRadius: 24,
      borderColor: theme.surface.glassBorder,
    },
    glowBackground: {
      position: "absolute",
      top: -50,
      left: -50,
      right: -50,
      bottom: -50,
      borderRadius: 100,
    },
    passcodeHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: theme.spacing.custom(10),
      marginBottom: theme.spacing.custom(28),
      zIndex: 1,
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.sm,
      borderRadius: 20,
      backgroundColor: theme.surface.glass,
    },
    passcodeLabel: {
      fontSize: 14,
      fontWeight: "700",
      textTransform: "uppercase",
      letterSpacing: 1,
      color: theme.primary.main,
    },
    passcodeDigits: {
      flexDirection: "row",
      gap: theme.spacing.custom(12),
      marginBottom: theme.spacing.lg,
      zIndex: 1,
    },
    passcodeDigit: {
      width: 60,
      height: 80,
      borderRadius: 16,
      borderWidth: 1,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      borderColor: theme.surface.glassBorder,
      backgroundColor: isDark
        ? "rgba(28, 84, 114, 0.2)"
        : "rgba(255,255,255,0.5)",
    },
    passcodeDigitText: {
      fontSize: 36,
      fontWeight: "800",
      letterSpacing: 2,
      color: theme.text.primary,
    },
    passcodeHint: {
      fontSize: 14,
      textAlign: "center",
      marginBottom: theme.spacing.sm,
      zIndex: 1,
      opacity: 0.7,
      color: theme.text.secondary,
    },
    updateTime: {
      fontSize: 12,
      fontStyle: "italic",
      zIndex: 1,
      opacity: 0.5,
    },
    errorText: {
      fontSize: 14,
      fontWeight: "600",
      color: theme.status.error,
    },
    buttonGroup: {
      marginTop: theme.spacing.custom(20),
      alignItems: "center",
    },
    refreshButton: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: theme.spacing.custom(20),
      paddingVertical: theme.spacing.custom(10),
      borderRadius: 12,
      backgroundColor: theme.primary.glow,
    },
    refreshButtonText: {
      fontSize: 14,
      fontWeight: "600",
      color: theme.primary.main,
    },
    refreshIcon: {
      marginRight: theme.spacing.sm,
    },
    instructionsCard: {
      borderRadius: 20,
      borderWidth: 1,
      padding: theme.spacing.custom(20),
      marginBottom: theme.spacing.lg,
    },
    instructionsTitle: {
      fontSize: 18,
      fontWeight: "700",
      marginBottom: theme.spacing.md,
    },
    instructionItem: {
      flexDirection: "row",
      alignItems: "flex-start",
      marginBottom: theme.spacing.custom(12),
    },
    instructionNumber: {
      width: 28,
      height: 28,
      borderRadius: 14,
      alignItems: "center",
      justifyContent: "center",
      marginRight: theme.spacing.custom(12),
      marginTop: theme.spacing.xxs,
    },
    instructionNumberText: {
      color: theme.text.primary,
      fontSize: 14,
      fontWeight: "bold",
    },
    instructionText: {
      flex: 1,
      fontSize: 15,
      lineHeight: 22,
    },
    doneButtonContainer: {
      marginTop: "auto",
      marginBottom: theme.spacing.custom(20),
    },
    doneButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: theme.spacing.custom(18),
      borderRadius: 20,
      gap: theme.spacing.custom(10),
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.3,
      shadowRadius: 16,
      elevation: 8,
    },
    doneButtonText: {
      color: theme.text.primary,
      fontSize: 18,
      fontWeight: "700",
      letterSpacing: 0.5,
    },
  };
});
