export const mutationKeys = {
  lectureJoin: ["lecture-join"],
  studentAttendanceSubmit: ["student-attendance-submit"],
  handleClassJoin: ["handle-class-join"],
  createLecture: ["create-lecture"],
  updateLectureByTeacher: ["update-lecuture-by-teacher"],
  rollNoSubmitStudent: ["roll-no-submit-student"],
  updateStudentClass: ["update-student-class"],
  sendForgotPasswordEmail: ["send-forgot-password-email"],
  logoutDeleteAccountLinkedin: ["logout-delete-account-linkedin"],
  signInLinkedIn: ["sign-in-linkedin"],
  manualAttendanceTeacher: ["manual-attendance-teacher"],
  handleCreateNewClass: ["create-new-class-teacher"],
  updateUserRole: ["update-user-role"],
  deleteAccountSettings: ["delete-account-settings"],
  logoutUser: ["logout-user"],
};
