import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  scrollContent: { padding: 20, paddingTop: 30 },
  headerSection: { marginBottom: 24 },
  title: {
    fontSize: 32,
    fontWeight: "800",
    marginBottom: 16,
    letterSpacing: -0.5,
  },
  classInfoCard: {
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    marginBottom: 8,
  },
  classInfoHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  classInfoLeft: { flexDirection: "row", alignItems: "center", flex: 1 },
  classInfoLabel: {
    fontSize: 12,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  classInfoValue: { fontSize: 18, fontWeight: "700" },
  editClassButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  subtitle: { fontSize: 18, fontWeight: "600", marginBottom: 24, opacity: 0.8 },
  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
    opacity: 0.7,
  },
  emptyText: { fontSize: 16, marginTop: 16, textAlign: "center" },
  refreshButton: { marginTop: 16, paddingVertical: 8, paddingHorizontal: 16 },
  refreshText: { fontSize: 16, fontWeight: "600" },
  lectureCard: {
    padding: 20,
    borderRadius: 24,
    borderWidth: 1,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
  },
  lectureCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 16,
  },
  headerLeftContent: { flexDirection: "row", flex: 1, marginRight: 12 },
  iconContainer: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  lectureInfo: { flex: 1, justifyContent: "center" },
  lectureCardTitle: {
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 4,
    letterSpacing: -0.3,
    lineHeight: 24,
  },
  lectureMetaRow: { flexDirection: "row", alignItems: "center" },
  lectureClassName: { fontSize: 14, fontWeight: "500", opacity: 0.7 },
  liveBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
  },
  liveDot: { width: 6, height: 6, borderRadius: 3, marginRight: 6 },
  liveBadgeText: { fontSize: 12, fontWeight: "700", letterSpacing: 0.5 },
  divider: { height: 1, width: "100%", marginBottom: 16, opacity: 0.5 },
  joinButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  joinButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "700",
    marginRight: 8,
  },
  joinIconContainer: {
    backgroundColor: "rgba(255,255,255,0.2)",
    borderRadius: 12,
    padding: 4,
    marginLeft: 8,
  },
  joinButtonIcon: { marginLeft: 4 },
  joinButtonLoader: { marginLeft: 8 },
  joinedContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    margin: 20,
    borderRadius: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
  },
  guardianIconOuter: {
    marginBottom: 32,
    shadowColor: "#4CAF50",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
  },
  guardianIconInner: {
    width: 100,
    height: 100,
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 4,
    borderColor: "rgba(255, 255, 255, 0.2)",
  },
  guardianTitle: {
    fontSize: 28,
    fontWeight: "800",
    marginBottom: 12,
    textAlign: "center",
    letterSpacing: -0.5,
  },
  guardianSubtitle: {
    fontSize: 16,
    textAlign: "center",
    marginBottom: 48,
    lineHeight: 24,
    opacity: 0.8,
  },
  passcodeCard: {
    width: "100%",
    padding: 24,
    borderRadius: 24,
    borderWidth: 1,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
  },
  passcodeLabel: {
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 12,
    textTransform: "uppercase",
    letterSpacing: 1,
    opacity: 0.7,
  },
  passcodeInput: {
    height: 56,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 16,
    fontSize: 20,
    fontWeight: "600",
    marginBottom: 20,
  },
  submitButton: {
    height: 56,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  submitButtonText: { color: "white", fontSize: 16, fontWeight: "700" },
  ongoingInfo: {
    width: "100%",
    alignItems: "center",
    marginBottom: 32,
    gap: 16,
  },
  trackingBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 20,
    backgroundColor: "rgba(76, 175, 80, 0.15)",
    gap: 8,
  },
  pulseDot: { width: 8, height: 8, borderRadius: 4 },
  trackingBadgeText: { fontSize: 14, fontWeight: "600" },
  waitText: { fontSize: 14, textAlign: "center", opacity: 0.7 },
  leaveButtonWrapper: { width: "100%", marginTop: 16 },
  leaveButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
    borderRadius: 16,
    gap: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  leaveButtonText: { color: "white", fontSize: 16, fontWeight: "700" },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContent: {
    width: "100%",
    maxWidth: 400,
    borderRadius: 24,
    borderWidth: 1,
    overflow: "hidden",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.1)",
  },
  modalTitle: { fontSize: 20, fontWeight: "bold" },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  modalBody: { padding: 20 },
  modalLabel: { fontSize: 14, fontWeight: "600", marginBottom: 8 },
  modalInput: { borderWidth: 1, borderRadius: 12, padding: 14, fontSize: 16 },
  modalFooter: {
    flexDirection: "row",
    gap: 12,
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.1)",
  },
  modalButton: { flex: 1, padding: 14, borderRadius: 12, alignItems: "center" },
  modalButtonText: { fontSize: 16, fontWeight: "600" },
  trackingIndicator: {
    marginTop: 24,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  trackingText: { fontSize: 14, fontStyle: "italic" },
});

export default styles;
